docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v3
  versions:
    - v3
nav:
  - Home: index.md
  - v3:
      - Overview: v3/overview.md
      - Installation: v3/installation.md
      - Configuration: v3/configuration.md
      - "Migrating From Previous Integrations": v3/migrating-from-previous-integrations.md
site_name: dot-doctrine-metadata
site_description: "DotKernel's component to provide metadata and strategies for extracting and rendering Doctrine entities."
repo_url: "https://github.com/dotkernel/dot-doctrine-metadata"
plugins:
  - search
